### PR TITLE
Implemented a hint button to call dfs #5

### PR DESCRIPTION
**Pull request by themousepotato**
Added a hint button to the program. TODO : increase the speed of execution of the game after calling the function.

### CODE REVIEW

**Comment by anirbunt** [comment]
Hey bro ,
how much time is it taking for the function to give it's output??
it took 1.3 sec for me on ide.geeksforgeek.com 
is your concern is to drop it down?
I can give you a hint if you actually wanted to do so

**Comment by themousepotato** [comment]
Try to run the new program that I've uploaded. As it comes under the game
loop, more time is needed for the execution I guess.

On Wed, Dec 20, 2017 at 11:18 PM, Anirudh vajjala <notifications@github.com>
wrote:

> Hey bro ,
> how much time is it taking for the function to give it's output??
> it took 1.3 sec for me on ide.geeksforgeek.com
> is your concern is to drop it down?
> I can give you a hint if you actually wanted to do so
>
Sure. You may.

**Comment by tibrewalpratik17** [comment]
do not send PR from master branch please make a local branch and send PR.

**Comment by themousepotato** [comment]
Ok

**Pull request closed without merging**
