### PR TITLE
Fixed: #1

### PR DESCRIPTION
**Pull request by aniketgattani**

### CODE REVIEW

**Comment by tibrewalpratik17** [comment]
@aniketgattani Can you update the README simultaneously? And also align the numbers in the center of the cell. And also while sending a pull request it will be great if you write Fixed: #issueNumber so that after I merge the PR the issue is automatically marked resolved.

**Comment by aniketgattani** [comment]
@tibrewalpratik17  I have aligned the text at the centre and modified the Readme as well Do have a look and plz tell me if u need something else. Also I changed the pull request header name as u told me to.

**Comment by tibrewalpratik17** [comment]
@aniketgattani can you please even change the screenshot in the README showing the center alignment of the numbers? And also add some more screenshots or GIFs to make it look more attractive.

**Comment by aniketgattani** [comment]
@tibrewalpratik17   I have added the screenshot. Hope so this will get merged now. Thanks :)

**Comment by tibrewalpratik17** [comment]
@aniketgattani  Great work. Just remove the second screenshot from the README as it still shows the number on the right. And sent it, I think it will be ready to merge then. If I find any other issue, I will request you to work on that. Thanks! Great going :)

**Comment by tibrewalpratik17** [comment]
@aniketgattani  Also after removing the second screenshot I would like you to squash your last 3 commits. Squashing commits is a great way to keep our version control usage clean.

**Comment by tibrewalpratik17** [comment]
@aniketgattani I think the numbers are going out of the box as they are increasing.
https://s17.postimg.org/d4gb745vj/Screenshot_from_2017-12-04_20_34_58.png

**Comment by aniketgattani** [comment]
@tibrewalpratik17  they arent dynamically adjusted. How do u suggest I should do that

**Comment by tibrewalpratik17** [comment]
One of the mentees have done it by making a separate dictionary for numbers.

**Comment by aniketgattani** [comment]
Ohh okay on it.

**Comment by tibrewalpratik17** [comment]
Good. But @aniketgattani  I think you got me wrong I just wanted you to squash the commits of ReadMes into one and the moveups into one. Basically I wanted 2 commits till now. Can you please do this.
Also can you please document a code a bit explaining about the codes and workflow. It looks nice and clean.

**Comment by aniketgattani** [comment]
Document as in do u want me to have comments in the code base or anything else ? Now the text is getting aligned at the center and the font is adjusting dynamically. I hope this would be ok.

**Comment by aniketgattani** [comment]
@tibrewalpratik17 can u review this please. I will make the changes accordingly

**Comment by tibrewalpratik17** [comment]
@aniketgattani I find this pretty good.. You can work on other issues if any bug comes up here I will tell you accordingly.. At present I am not merging any of the PRs because others are working on same problem and I want them to learn.. once others complete their work I will merge one of the PRs which I find best accordingly...

**Comment by aniketgattani** [comment]
But i opened this the earliest so shouldnt you be giving the preference on first come first serve basis. I have already made a lot of modifications and am willing to make more if u say so.

**Comment by tibrewalpratik17** [comment]
@aniketgattani this is not a competition... and surely I would be very happy to merge your code and I see that you have done great and if found others would have done the same thing I will surely merge your code.. but don't take this as a competition.. open source is where people come together to contribute and not compete..hope so you get this right

**Comment by aniketgattani** [comment]
Really sorry if u felt my conduct was bad but it was just that I wanted my PR to get merged because I did work lot on this. Yes I did learn a lot of stuffs (very impt for open source) such as creating a proper PR etc. And hence wanted to give in my best if needed. Surely I would like to be an asset by being the major contributor. Sorry once again.

**Comment by tibrewalpratik17** [comment]
@aniketgattani there is nothing to be sorry about... I know this feeling.. but you must remember that open source is all about learning and contributing :)

**Comment by tibrewalpratik17** [comment]
Hey @aniketgattani  due to your inactivity in the google group I have removed you from the group and I feel that you should be more open towards conversation. I will not merge your PR until further explanation. I want you to mail me the reason.

**Comment by aniketgattani** [comment]
Hi pratik i did submit two of my PR's in the beginning and I was waiting
for them to be merged or atleast someone else's. So that i would know what
else can be done. Since there was no progress (in terms of PRs) in the
project i felt sending more PR's would increase ur burden so I felt i
should wait a bit and then send in more PRs. Hence the inactivity.
Extremely sorry though I should have helped the others but i wasnt even
receiving notifications from the google group as well idk why. From now I
will give in my inputs nd be active in the group sorry.

**Comment by tibrewalpratik17** [comment]
@aniketgattani I did ask you to talk in the google group at the very beginning and I also mentioned you the reason of not accepting PRs. I know that you are willing to contribute that is why I asked you to provide me a reason and send me request for adding you in the google group asap and talk to your friends on issues you can work on.

**Comment by aniketgattani** [comment]
Yeah sure i dont have my PC right now will do this tomorrow morning. Thanks

On Dec 21, 2017 00:58, "Pratik Tibrewal" <notifications@github.com> wrote:

@aniketgattani <https://github.com/aniketgattani> I did ask you to talk in
the google group at the very beginning and I also mentioned you the reason
of not accepting PRs. I know that you are willing to contribute that is why
I asked you to provide me a reason and send me request for adding you in
the google group asap and talk to your friends on issues you can work on.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tibrewalpratik17/2048_/pull/10#issuecomment-353158684>,
or mute the thread

**Pull request merged**
