### PR TITLE
Score Bar added 

### PR DESCRIPTION
**Pull request by aniketgattani**
I have added a score bar feature to the existing game. Let me know if you need anything else and I will make it accordingly.

### CODE REVIEW

**Comment by tibrewalpratik17** [comment]
@aniketgattani it is always suggested that you carry out individual tasks in different branches made from the master. What you did was you made this branch from your branch `local` which included the commits for moveup and other changes. Now that if you have changed your pervious PR. it will show me a merge conflict while merging this branch. Think about it. So just add the ScoreBoard commit in a branch with only this change made and not the moveup one.

**Comment by tibrewalpratik17** [comment]
Closing this PR.

**Comment by aniketgattani** [comment]
Okay I thought maybe if I dont make these changes in this branch you will face problems while merging anyways sending a new PR to you. Thanks :)

**Comment by tibrewalpratik17** [comment]
@aniketgattani but you need to understand that what if your first PR had some errors that will be automatically copied to your second PR too so your PRs should be independent of each other.

**Comment by aniketgattani** [comment]
Yeah thats quite r8 anyways I sent u a new PR please check that.

**Pull request closed without merging**
