### PR TITLE
Add left, right and up movement

### PR DESCRIPTION
**Pull request by tmw9**

### CODE REVIEW

**Comment by tibrewalpratik17** [comment]
@tmw98 can you even change the README file by replacing the issue from the issues list and also adding some screenshots of your code by replacing the previous screenshot. And also it will be great if you align the numbers in the center and also reduce the font size of the larger numbers.

**Comment by tmw9** [comment]
Sure. Will do that ASAP.

**Comment by tmw9** [comment]
Changed font size as the numbers increase, Added end game and win game screens almost same as start game, will add scoreboard once scoring is done. And also up, left and right movement done. README.md updated with more screenshots.

**Comment by tibrewalpratik17** [comment]
@tmw98 Awesome! Great going! :)

**Comment by tibrewalpratik17** [comment]
Can you even remove the second screenshot?

**Comment by tmw9** [comment]
Done

**Comment by tibrewalpratik17** [comment]
Hey @tmw98 due to your inactivity in the google group I have removed you from the group and I feel that you should be more open towards conversation. I will not merge your PR until further explanation. I want you to mail me the reason.

**Comment by tmw9** [comment]
You were not accepting any pull requests so that's the reason I stopped
contributing and was inactive

**Comment by tibrewalpratik17** [comment]
Well @tmw98 first of all I asked you to send a mail and not reply in comments... and second point is that you are not the only one who are working on this project there are other mentees too... and do you realize if I accept your PR then that issue is resolved and no one else gets the opportunity of working on that issue and learn.. I even told this in the google group but if you are inactive and are not reading mails then I can't help about it. And it's okay if you do not want to contribute, it's your will.

**Comment by tmw9** [comment]
Oh sorry. I understand. It's my fault, I wasn't much active in Google
groups so sorry for that, but I have ICPC coming up 26, 27th December
amritapuri. Need to prepare for that.

**Comment by tibrewalpratik17** [comment]
All the best for your icpc.. :+1:

**Pull request closed without merging**
