### PR TITLE
Game over code and 4096 and 8192 box

### PR DESCRIPTION
**Pull request by nuclode**
1. Added screen for a game over with its working.
2. Added 4096 and 8192 boxes.

### CODE REVIEW

**Comment by tibrewalpratik17** [comment]
Yaa sure go for it...

**Comment by nuclode** [comment]
I have done this...

**Comment by tibrewalpratik17** [comment]
@nuclode Great going:)

**Comment by tibrewalpratik17** [comment]
Hey @nuclode you did the same mistake here I think you added these features on your previous commit and sent a PR please do this separately.

**Pull request closed without merging**
